# -*- coding: utf-8 -*-
"""automate_Nina Ainur Rachmah.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ruKIP0rR-5H0j8lCG1jdYhHmU7dn7VH5
"""

import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler

# 1. HANDLE MISSING VALUES
def handle_missing_values(df: pd.DataFrame) -> pd.DataFrame:
    """
    Menangani missing values dengan:
    - Mengganti nilai 'unknown' menjadi NaN
    - Imputasi: mode untuk kategorikal, median untuk numerik
    """
    df = df.copy()

    # Replace 'unknown' with NaN
    for col in df.columns:
        if df[col].dtype == 'object':
            df[col] = df[col].replace('unknown', np.nan)

    # Imputation
    for col in df.columns:
        if df[col].dtype == 'object':
            df[col] = df[col].fillna(df[col].mode()[0])
        else:
            df[col] = df[col].fillna(df[col].median())

    return df

# 2. REMOVE DUPLICATES
def remove_duplicates(df: pd.DataFrame) -> pd.DataFrame:
    """Menghapus data duplikat."""
    return df.drop_duplicates()

# 3. DETECT FEATURE TYPES
def detect_feature_types(df: pd.DataFrame):
    """Mendeteksi fitur numerik dan kategorikal."""
    categorical_cols = df.select_dtypes(include='object').columns.tolist()
    numeric_cols = df.select_dtypes(include=['int64', 'float64']).columns.tolist()
    return categorical_cols, numeric_cols

# 4. HANDLE OUTLIERS (IQR METHOD)
def handle_outliers_iqr(df: pd.DataFrame, numeric_cols: list) -> pd.DataFrame:
    """Menghapus outlier numerik menggunakan metode IQR."""
    df = df.copy()

    for col in numeric_cols:
        Q1 = df[col].quantile(0.25)
        Q3 = df[col].quantile(0.75)
        IQR = Q3 - Q1
        lower_bound = Q1 - 1.5 * IQR
        upper_bound = Q3 + 1.5 * IQR

        df = df[(df[col] >= lower_bound) & (df[col] <= upper_bound)]

    return df

# 5. FEATURE ENGINEERING
def feature_engineering(df: pd.DataFrame, categorical_cols: list):
    """Melakukan feature engineering (binning umur)."""
    df = df.copy()

    if 'age' in df.columns:
        df['age_group'] = pd.cut(
            df['age'],
            bins=[0, 25, 40, 60, 100],
            labels=['young', 'adult', 'middle-aged', 'senior']
        )
        categorical_cols.append('age_group')

    return df, categorical_cols


# 6. ENCODING
def encode_features(df: pd.DataFrame, categorical_cols: list) -> pd.DataFrame:
    """
    - Target encoding untuk variabel target 'deposit'
    - One-hot encoding untuk fitur kategorikal lainnya
    """
    df = df.copy()

    # Target encoding
    df['deposit'] = df['deposit'].map({'yes': 1, 'no': 0})

    if 'deposit' in categorical_cols:
        categorical_cols.remove('deposit')

    # One-hot encoding
    df = pd.get_dummies(df, columns=categorical_cols, drop_first=True)

    return df

# 7. FEATURE SCALING
def scale_numeric_features(df: pd.DataFrame, numeric_cols: list) -> pd.DataFrame:
    """Melakukan standardisasi fitur numerik."""
    df = df.copy()

    scaler = StandardScaler()
    df[numeric_cols] = scaler.fit_transform(df[numeric_cols])

    return df

# 8. MAIN PREPROCESSING PIPELINE
def preprocess_data(df: pd.DataFrame) -> pd.DataFrame:
    """
    Pipeline preprocessing otomatis sesuai eksperimen:
    1. Handle missing values
    2. Remove duplicates
    3. Deteksi fitur
    4. Outlier handling (IQR)
    5. Feature engineering
    6. Encoding
    7. Scaling

    Parameters:
    df : pd.DataFrame
        Data mentah

    Returns:
    pd.DataFrame
        Data siap digunakan untuk training model
    """

    df = df.copy()

    df = handle_missing_values(df)
    df = remove_duplicates(df)

    categorical_cols, numeric_cols = detect_feature_types(df)

    df = handle_outliers_iqr(df, numeric_cols)
    df, categorical_cols = feature_engineering(df, categorical_cols)
    df = encode_features(df, categorical_cols)
    df = scale_numeric_features(df, numeric_cols)

    return df